# Generated by Django 4.0.4 on 2022-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.IntegerField(choices=[(1, '10:00 am -11:00 am'), (2, '11:00 am - 12:00 am'), (3, '12:00 pm- 1:00 pm'), (4, '1:00 pm - 2:00 pm'), (5, '2:00 pm- 3:00 pm'), (6, '3:00 pm - 4:00 pm'), (7, '4:00 pm - 5:00 pm')]),
        ),
    ]
