# Generated by Django 4.0.4 on 2022-05-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_slot_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('decription', models.TextField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'complite'), (2, 'absent'), (3, 'cancel')], default=0)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.slot')),
            ],
        ),
    ]
