# Generated by Django 4.0.4 on 2022-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_alter_appointment_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.IntegerField(choices=[(1, '10:00 am -11:00 am'), (2, '11:00 am - 12:00 pm'), (3, '12:00 pm- 1:00 pm'), (4, '1:00 pm - 2:00 pm'), (5, '2:00 pm- 3:00 pm'), (6, '3:00 pm - 4:00 pm'), (7, '4:00 pm - 5:00 pm')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(default='profile.png', upload_to='profile'),
        ),
    ]
